import { useRef, useState } from "react";
import { Bot, BrainCircuit, CheckCircle2, Clock3, Cpu, FileLock2, Folder, GitBranch, RefreshCw, ShieldAlert, ShieldCheck, Sparkles, Workflow, X } from "lucide-react";
import { createTeamSpaceStore, type TeamSpaceStore } from "./lib/team/store";
import type { ActivityEvent, Approval, Resource } from "./lib/team/types";
import { askAssistant, buildProjectContext, type AssistantAnswer } from "./lib/team/project-assistant";
import { useI18n } from "./i18n";

const modeLabel: Record<Resource["collaboration_mode"], string> = { realtime_edit: "实时协作", mergeable: "可合并", git: "Git", exclusive_lock: "排他锁", versioned_file: "版本文件" };
const modeTone: Record<Resource["collaboration_mode"], string> = { realtime_edit: "bg-sky-500/10 text-sky-700 dark:text-sky-300", mergeable: "bg-violet-500/10 text-violet-700 dark:text-violet-300", git: "bg-orange-500/10 text-orange-700 dark:text-orange-300", exclusive_lock: "bg-rose-500/10 text-rose-700 dark:text-rose-300", versioned_file: "bg-slate-500/10 text-slate-600 dark:text-slate-300" };
const aiStateLabel = { idle: "空闲", locked: "持锁中", pending_approval: "待审批" };
const aiStateTone = { idle: "bg-slate-500/10 text-slate-600 dark:text-slate-300", locked: "bg-rose-500/10 text-danger-700 dark:text-danger-400", pending_approval: "bg-warning-500/10 text-warning-700 dark:text-warning-400" };
const aiActorTone = ["border-violet-500/55", "border-sky-500/55", "border-emerald-500/55", "border-orange-500/55", "border-fuchsia-500/55"];
function shortHash(value: string | null) { return value ? `${value.slice(0, 12)}${value.length > 12 ? "…" : ""}` : "—"; }
function icon(resource: Resource) { return resource.collaboration_mode === "git" ? <GitBranch size={17} /> : resource.type === "folder" ? <Folder size={17} /> : <FileLock2 size={17} />; }
function actorTone(event: ActivityEvent) { return event.actor_is_ai ? aiActorTone[Array.from(event.actor).reduce((sum, char) => sum + char.charCodeAt(0), 0) % aiActorTone.length] : "border-slate-400/60"; }

/** 本地演示页：留出 provider 接口，尚不做远端权限隔离或真实文件同步。 */
export function TeamSpace() {
  const { t } = useI18n();
  const storeRef = useRef<TeamSpaceStore | null>(null);
  if (!storeRef.current) storeRef.current = createTeamSpaceStore();
  const store = storeRef.current;
  const [workspaceId, setWorkspaceId] = useState("ws-hequbing");
  const [operatorId, setOperatorId] = useState(() => store.listMemberships("ws-hequbing")[0]?.user_id || "");
  const [aiFilter, setAiFilter] = useState("all");
  const [expandedDiff, setExpandedDiff] = useState<string | null>(null);
  const [tick, setTick] = useState(0);
  const [notice, setNotice] = useState<string | null>(null);
  const [assistantQuestion, setAssistantQuestion] = useState("");
  const [assistantAnswer, setAssistantAnswer] = useState<AssistantAnswer | null>(null);
  const [assistantBusy, setAssistantBusy] = useState(false);
  const workspace = store.listWorkspaces().find((item) => item.id === workspaceId);
  const members = store.listMemberships(workspaceId);
  const project = store.listProjects(workspaceId)[0];
  const resources = store.listResources(project?.id);
  const approvals = store.listApprovals(project?.id);
  const aiMembers = store.listAiMemberStates(workspaceId);
  const activity = store.listActivity(project?.id).filter((event) => aiFilter === "all" || event.actor === aiFilter).slice(0, 12);
  const refresh = (message?: string) => { setTick((value) => value + 1); setNotice(message || null); };
  const run = async (work: () => Promise<unknown>, success: string) => { try { await work(); refresh(success); } catch (error) { setNotice(error instanceof Error ? error.message : String(error)); } };
  void tick;

  return <div className="max-w-6xl mx-auto space-y-5 pb-8">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-card border border-ink-6 bg-bg-1 p-5 shadow-card">
      <div><p className="text-xs text-ink-3">{t("协作机制原型 · 本机演示数据，尚未打通多设备协作")}</p><h1 className="mt-1 text-xl font-semibold text-ink-0">{workspace?.name || "工作空间"}</h1></div>
      <div className="flex flex-wrap gap-2"><select value={operatorId} onChange={(event) => setOperatorId(event.target.value)} aria-label="当前操作者" className="rounded-lg border border-ink-6 bg-bg-0 px-3 py-2 text-sm text-ink-1 outline-none">{members.map((member) => <option key={member.user_id} value={member.user_id}>{member.user_id}{member.is_ai ? " · AI" : ""}</option>)}</select><select value={workspaceId} onChange={(event) => { const nextWorkspace = event.target.value; setWorkspaceId(nextWorkspace); setOperatorId(store.listMemberships(nextWorkspace)[0]?.user_id || ""); refresh(); }} className="rounded-lg border border-ink-6 bg-bg-0 px-3 py-2 text-sm text-ink-1 outline-none">{store.listWorkspaces().map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    </div>
    {notice && <div className="flex items-center justify-between rounded-lg border border-accent/25 bg-accent/10 px-4 py-2 text-sm text-accent-700 dark:text-accent-400"><span>{notice}</span><button onClick={() => setNotice(null)} aria-label="关闭提示"><X size={15} /></button></div>}
    {!project ? <div className="rounded-card border border-dashed border-ink-5 bg-bg-1 p-10 text-center text-sm text-ink-3">个人空间原型：切换到「贺去病科技」查看融资计划协作闭环。</div> : <>
      <section className="grid gap-3 sm:grid-cols-3"><Metric label="项目" value={project.name} /><Metric label="资源" value={`${resources.length} 项`} /><Metric label="待人工审批" value={`${approvals.filter((item) => item.status === "pending").length} 项`} /></section>
      <LongTaskSituationBoard projectName={project.name} aiMembers={aiMembers} approvals={approvals} activity={activity} onFilter={(actor) => setAiFilter(actor)} />
      <section className="rounded-card border border-ink-6 bg-bg-1 p-4 shadow-card"><div className="mb-3 flex items-center gap-2"><Sparkles size={17} className="text-accent"/><h2 className="font-semibold text-ink-0">AI 成员协同</h2><span className="text-xs text-ink-3">状态由 Lease 与审批队列实时计算</span></div><div className="flex flex-wrap gap-2">{aiMembers.map((member) => <div key={member.user_id} className="flex items-center gap-2 rounded-lg border border-ink-6 bg-bg-0 px-3 py-2 text-xs"><span className="font-medium text-ink-1">{member.user_id}</span><span className="text-ink-3">{member.role}</span><span className={`rounded-full px-2 py-0.5 ${aiStateTone[member.state]}`}>{aiStateLabel[member.state]}</span></div>)}</div></section>
      <section className="rounded-card border border-ink-6 bg-bg-1 p-5 shadow-card"><div className="mb-4 flex items-center gap-2"><Folder size={18} className="text-accent" /><h2 className="font-semibold text-ink-0">项目文件 · {project.name}</h2></div><div className="divide-y divide-ink-6">{resources.map((resource) => <ResourceCard key={resource.id} resource={resource} store={store} operatorId={operatorId} run={run} />)}</div></section>
      <section className="rounded-card border border-accent/25 bg-bg-1 p-5 shadow-card"><div className="flex items-center gap-2"><Sparkles size={18} className="text-accent"/><h2 className="font-semibold text-ink-0">AI 顾问</h2><span className="text-xs text-ink-3">只读取资源元数据、锁与审计摘要</span></div><div className="mt-3 flex gap-2"><input value={assistantQuestion} onChange={(event) => setAssistantQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void (async () => { if (!assistantQuestion.trim() || assistantBusy) return; setAssistantBusy(true); setAssistantAnswer(await askAssistant(project.id, assistantQuestion.trim(), store)); setAssistantBusy(false); })(); }} placeholder="例如：项目当前最大的协作风险是什么？" className="min-w-0 flex-1 rounded-lg border border-ink-6 bg-bg-0 px-3 py-2 text-sm text-ink-1 outline-none"/><button disabled={assistantBusy || !assistantQuestion.trim()} onClick={() => void (async () => { setAssistantBusy(true); setAssistantAnswer(await askAssistant(project.id, assistantQuestion.trim(), store)); setAssistantBusy(false); })()} className="rounded-lg bg-accent px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{assistantBusy ? "分析中…" : "提问"}</button></div>{assistantAnswer && <div className="mt-3 rounded-lg border border-ink-6 bg-bg-0 p-3"><p className="whitespace-pre-wrap text-sm leading-6 text-ink-1">{assistantAnswer.answer}</p><div className="mt-3 flex flex-wrap items-center gap-2"><button onClick={() => void run(() => store.createAssistantDraft(project.id, assistantAnswer.answer.slice(0, 500), assistantAnswer.draftChanges), "AI 草稿已进入人工审批队列") } className="rounded bg-bg-2 px-3 py-1.5 text-xs text-ink-1 hover:bg-bg-3">根据项目现状生成 AI 草稿</button>{assistantAnswer.offline && <span className="text-xs text-ink-3">离线摘要模式</span>}</div></div>} {!assistantAnswer && <p className="mt-3 text-xs leading-5 text-ink-3">{buildProjectContext(project.id, store).factSummary}</p>}</section>
      <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-card border border-ink-6 bg-bg-1 p-5 shadow-card"><div className="mb-4 flex items-center gap-2"><ShieldCheck size={18} className="text-accent"/><h2 className="font-semibold text-ink-0">人工审批队列</h2></div><div className="space-y-3">{approvals.map((approval) => <div key={approval.id} className="rounded-lg border border-ink-6 bg-bg-0 p-3"><div className="flex gap-2"><div className="min-w-0 flex-1"><p className="font-medium text-ink-1">{approval.title}</p><p className="mt-1 text-xs leading-5 text-ink-3">{approval.summary}</p><p className="mt-2 text-xs text-ink-3">草稿：{approval.pending_files.map((file) => `${file.resource_id} · ${file.revision_id}`).join("；")}</p>{approval.receipt_hash && <p className="mt-1 font-mono text-[11px] text-ink-3">Receipt {shortHash(approval.receipt_hash)}</p>}</div><span className="h-fit rounded-full bg-warning-500/15 px-2 py-0.5 text-[11px] text-warning-700 dark:text-warning-400">{approval.status === "pending" ? "待审批" : approval.status === "approved" ? "已通过" : "已拒绝"}</span></div>{approval.draft_diff && <><button className="mt-3 text-xs text-accent hover:underline" onClick={() => setExpandedDiff(expandedDiff === approval.id ? null : approval.id)}>{expandedDiff === approval.id ? "收起草稿 diff" : "展开草稿 diff"}</button>{expandedDiff === approval.id && <DraftDiff approval={approval} />}</>}{approval.status === "pending" && <div className="mt-3 flex gap-2"><button className="rounded bg-emerald-600 px-2.5 py-1.5 text-xs text-white" onClick={() => run(() => store.approveApproval(approval.id, operatorId), "审批已通过，Receipt 已写入审计")}>通过</button><button className="rounded border border-ink-5 px-2.5 py-1.5 text-xs text-ink-2" onClick={() => run(() => store.rejectApproval(approval.id, operatorId), "审批已拒绝，Receipt 已留痕")}>拒绝</button></div>}</div>)}</div></section>
      <section className="rounded-card border border-ink-6 bg-bg-1 p-5 shadow-card"><div className="mb-4 flex flex-wrap items-center gap-2"><Clock3 size={18} className="text-accent"/><h2 className="font-semibold text-ink-0">活动审计时间线</h2><select value={aiFilter} onChange={(event) => setAiFilter(event.target.value)} className="ml-auto rounded border border-ink-6 bg-bg-0 px-2 py-1 text-xs text-ink-2"><option value="all">全部成员</option>{aiMembers.map((member) => <option key={member.user_id} value={member.user_id}>只看 {member.user_id}</option>)}</select></div><div className="space-y-3">{activity.map((event) => <Timeline key={event.id} event={event} />)}{activity.length === 0 && <p className="text-xs text-ink-3">暂无该 AI 的活动记录</p>}</div></section></div>
      <button className="flex items-center gap-1 text-xs text-ink-3 hover:text-ink-1" onClick={() => { store.resetDemo(); refresh("演示数据已重置"); }}><RefreshCw size={13}/>重置演示数据</button>
    </>}
  </div>;
}
function ResourceCard({ resource, store, operatorId, run }: { resource: Resource; store: TeamSpaceStore; operatorId: string; run: (work: () => Promise<unknown>, success: string) => Promise<void> }) { const lock = store.getLock(resource.id); const active = !!lock && new Date(lock.expires_at).getTime() > Date.now(); return <div className="py-3 first:pt-0"><div className="flex flex-wrap items-center gap-2"><span className="text-ink-3">{icon(resource)}</span><span className="font-medium text-ink-1">{resource.name}</span><span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${modeTone[resource.collaboration_mode]}`}>{modeLabel[resource.collaboration_mode]}</span><span className="text-xs text-ink-3">{resource.current_revision_id}</span></div>{resource.collaboration_mode === "exclusive_lock" && <div className="mt-2 flex flex-wrap items-center gap-2 rounded-lg bg-bg-0 px-3 py-2 text-xs text-ink-2"><FileLock2 size={14} className={active ? "text-rose-500" : "text-emerald-500"}/>{lock && active ? <><span>已由 <b>{lock.holder_id}</b> @ {lock.device_id} 签出</span><span>到期 {new Date(lock.expires_at).toLocaleTimeString()}</span><span>心跳 {new Date(lock.heartbeat_at).toLocaleTimeString()}</span><button className="ml-auto rounded bg-bg-2 px-2 py-1 hover:bg-bg-3" onClick={() => run(() => store.heartbeatLock(resource.id, operatorId), "租约心跳已续期")}>续租</button><button className="rounded border border-rose-500/40 px-2 py-1 text-rose-700 hover:bg-rose-500/10 dark:text-rose-300" onClick={() => run(() => store.tryAcquireExclusiveLock(resource.id, operatorId, `pc-${operatorId}`), `${operatorId} 已接管过期 Lease`)}>请求接管</button><button className="rounded bg-ink-0 px-2 py-1 text-bg-1 hover:opacity-90" onClick={() => run(() => store.unlockResource(resource.id, operatorId), "已签入，Lease 已释放")}>签入</button></> : lock ? <><span><b>{lock.holder_id}</b> 的 Lease 已于 {new Date(lock.expires_at).toLocaleTimeString()} 过期</span><button className="ml-auto rounded bg-rose-600 px-2 py-1 text-white hover:opacity-90" onClick={() => run(() => store.tryAcquireExclusiveLock(resource.id, operatorId, `pc-${operatorId}`), `${operatorId} 已接管过期 Lease`)}>请求接管</button></> : <><span>未签出，可由当前操作者取得排他编辑权</span><button className="ml-auto rounded bg-ink-0 px-2 py-1 text-bg-1 hover:opacity-90" onClick={() => run(() => store.lockResource(resource.id, operatorId, `pc-${operatorId}`), `${operatorId} 已签出并取得 Lease`)}>签出</button></>}</div>}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-card border border-ink-6 bg-bg-1 p-4 shadow-card"><p className="text-xs text-ink-3">{label}</p><p className="mt-1 font-semibold text-ink-0">{value}</p></div>; }
function LongTaskSituationBoard({ projectName, aiMembers, approvals, activity, onFilter }: { projectName: string; aiMembers: ReturnType<TeamSpaceStore["listAiMemberStates"]>; approvals: Approval[]; activity: ActivityEvent[]; onFilter: (actor: string) => void }) {
  const pending = approvals.filter((item) => item.status === "pending");
  const active = aiMembers.filter((item) => item.state !== "idle");
  const state = pending.length ? "awaiting_human" : active.length ? "running" : "verified";
  const stateLabel = state === "awaiting_human" ? "等待人工审批" : state === "running" ? "执行中" : "已验证";
  const stateTone = state === "awaiting_human" ? "text-warning-700 dark:text-warning-300" : state === "running" ? "text-sky-700 dark:text-sky-300" : "text-emerald-700 dark:text-emerald-300";
  const latest = activity[0];
  return <section className="overflow-hidden rounded-card border border-violet-500/30 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-violet-500/10 via-bg-1 to-bg-1 p-5 shadow-card">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-violet-700 dark:text-violet-300">长程计算 · 任务态势图（local-provider）</p><h2 className="mt-1 flex items-center gap-2 text-lg font-semibold text-ink-0"><Cpu size={19} className="text-accent"/>AI 主板 · {projectName}</h2><p className="mt-1 text-xs text-ink-3">视觉只投影 Lease、审批和审计事件；不另造状态，不把演示数据伪装成真实模型调用。</p></div><div className={`rounded-full border border-current/20 bg-bg-0 px-3 py-1 text-xs font-medium ${stateTone}`}>{stateLabel}</div></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_1.25fr_1fr]">
      <div className="space-y-2"><BoardChip icon={<BrainCircuit size={15}/>} title="Context RAM" detail={latest ? `${latest.action} · ${latest.resource_id || "项目"}` : "等待任务上下文"} /><BoardChip icon={<Bot size={15}/>} title="模型 CPU" detail={`${aiMembers.length} 位 AI 成员 · ${active.length} 位活跃`} /><BoardChip icon={<Workflow size={15}/>} title="本源北桥" detail="任务拆解 / 上下文编译" /></div>
      <div className="relative min-h-56 rounded-xl border border-violet-400/30 bg-bg-0/70 p-4"><div className="absolute inset-x-8 top-1/2 h-px bg-gradient-to-r from-transparent via-violet-400/60 to-transparent"/><div className="absolute inset-y-8 left-1/2 w-px bg-gradient-to-b from-transparent via-violet-400/60 to-transparent"/><div className="relative z-10 mx-auto flex h-24 w-24 flex-col items-center justify-center rounded-2xl border border-accent/60 bg-bg-1 text-center shadow-[0_0_32px_rgba(139,92,246,.25)]"><span className="text-[10px] text-ink-3">本象任务核</span><span className="mt-1 text-xs font-semibold text-ink-0">{stateLabel}</span><span className="mt-1 text-[10px] text-ink-3">{activity.length} 条证据事件</span></div><div className="mt-5 grid grid-cols-2 gap-2">{aiMembers.slice(0, 4).map((member) => <button key={member.user_id} onClick={() => onFilter(member.user_id)} className="rounded-lg border border-ink-6 bg-bg-1/90 px-2 py-2 text-left transition hover:border-violet-400/60"><span className="block truncate text-xs font-medium text-ink-1">{member.user_id}</span><span className="mt-1 block text-[10px] text-ink-3">{member.role} · {aiStateLabel[member.state]}</span></button>)}</div></div>
      <div className="space-y-2"><BoardChip icon={<ShieldAlert size={15}/>} title="影核 · 人审闸门" detail={pending.length ? `${pending.length} 项高风险动作待批准` : "无待审批高风险动作"} tone={pending.length ? "warning" : "success"}/><BoardChip icon={<CheckCircle2 size={15}/>} title="本境" detail="经验 / SOP 只在验证后沉淀" tone="success"/><BoardChip icon={<Workflow size={15}/>} title="本源南桥" detail="文件 / 工具 / API 动作经授权执行"/></div>
    </div>
    <p className="mt-4 border-t border-ink-6 pt-3 text-[11px] text-ink-3">点击任一 AI 角色可过滤下方审计时间线；Token、成本和 OTLP Trace 见「运行中心」。P0 将把同一 task_id / trace_id 接入此视图。</p>
  </section>;
}
function BoardChip({ icon, title, detail, tone = "default" }: { icon: React.ReactNode; title: string; detail: string; tone?: "default" | "warning" | "success" }) { const style = tone === "warning" ? "border-warning-500/35 text-warning-700 dark:text-warning-300" : tone === "success" ? "border-emerald-500/35 text-emerald-700 dark:text-emerald-300" : "border-ink-6 text-ink-2"; return <div className={`rounded-lg border bg-bg-0/75 p-3 ${style}`}><div className="flex items-center gap-2 text-xs font-medium">{icon}{title}</div><p className="mt-1 text-[11px] leading-5 text-ink-3">{detail}</p></div>; }
function DraftDiff({ approval }: { approval: Approval }) { const diff = approval.draft_diff!; const tone = { insert: "border-emerald-500/25 bg-emerald-500/10", delete: "border-rose-500/25 bg-rose-500/10", replace: "border-amber-500/25 bg-amber-500/10" }; const label = { insert: "新增", delete: "删除", replace: "替换" }; return <div className="mt-2 rounded border border-accent/20 bg-bg-1 p-3 text-xs"><p className="mb-2 font-medium text-ink-1">AI 输出在草稿区，合并需人工批准 · {diff.resource_id} · {diff.revision_from} → {diff.revision_to}</p><div className="space-y-2">{diff.changes.map((change, index) => <div key={`${change.line_or_section}-${index}`} className={`rounded border px-2 py-1.5 ${tone[change.action]}`}><span className="font-medium">{label[change.action]} · {change.line_or_section}</span><p className="mt-1 leading-5 text-ink-2">{change.snippet}</p></div>)}</div></div>; }
function Timeline({ event }: { event: ActivityEvent }) { return <div className={`border-l-2 ${actorTone(event)} pl-3 text-xs`}><p className="font-medium text-ink-1">{event.actor}{event.actor_is_ai ? " · AI" : ""} · {event.action}</p><p className="mt-1 text-ink-3">{event.resource_id || "项目"}{event.revision_id ? ` · ${event.revision_id}` : ""}</p><p className="mt-1 font-mono text-[10px] text-ink-4">HLC {event.hlc} · Receipt {shortHash(event.receipt_hash)}</p></div>; }
